In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [2]:
df=pd.DataFrame({
    'color':['red','blue','green','green','red','blue']
})

In [3]:
df

   color
0    red
1   blue
2  green
3  green
4    red
5   blue

In [4]:
encoder=OneHotEncoder()

In [5]:
encoded=encoder.fit_transform(df[['color']]).toarray()

In [6]:
encoded

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [7]:
encoded_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())
encoded_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [8]:
encoder.transform([['blue']]).toarray()

C:\Users\KASHISH\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [9]:
encoder.get_feature_names_out()

array(['color_blue', 'color_green', 'color_red'], dtype=object)

In [10]:
pd.concat([df,encoded_df],axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0

In [11]:
from sklearn.preprocessing import LabelEncoder

In [12]:
encoder=LabelEncoder()

In [13]:
encoder.fit_transform(df[['color']])

C:\Users\KASHISH\AppData\Roaming\Python\Python312\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 1, 2, 0])

In [14]:
encoder.transform([['red']])

C:\Users\KASHISH\AppData\Roaming\Python\Python312\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([2])

In [15]:
df=pd.DataFrame({
    'size':['small','medium','large','small','large','medium']
})

In [16]:
df

     size
0   small
1  medium
2   large
3   small
4   large
5  medium

In [17]:
from sklearn.preprocessing import OrdinalEncoder

In [20]:
encoder=OrdinalEncoder(categories=[['small','medium','large']])

In [21]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [0.],
       [2.],
       [1.]])

In [23]:
encoder.transform([['large']])

C:\Users\KASHISH\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[2.]])

In [24]:
df=pd.DataFrame({
    'city':['New York','London','Paris','Tokyo','New York','Paris'],
    'price':[200,150,300,250,180,320],
    })

In [25]:
df

       city  price
0  New York    200
1    London    150
2     Paris    300
3     Tokyo    250
4  New York    180
5     Paris    320

In [26]:
mean_price=df.groupby('city')['price'].mean().to_dict()

In [27]:
mean_price

{'London': 150.0, 'New York': 190.0, 'Paris': 310.0, 'Tokyo': 250.0}

In [28]:
df['city_encoded']=df['city'].map(mean_price)

In [34]:
df

       city  price  city_encoded
0  New York    200         190.0
1    London    150         150.0
2     Paris    300         310.0
3     Tokyo    250         250.0
4  New York    180         190.0
5     Paris    320         310.0

In [33]:
new_df=df[['price','city_encoded']]

In [35]:
new_df

   price  city_encoded
0    200         190.0
1    150         150.0
2    300         310.0
3    250         250.0
4    180         190.0
5    320         310.0