In [1]:
import pandas as pd

In [5]:
data=[1,2,3,4,5]
series=pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [6]:
data=[10,20,30]
index=['a','b','c']
series=pd.Series(data,index=index)
print(series)

a    10
b    20
c    30
dtype: int64

In [4]:
data={'a':1,'b':2,'c':3}
series_dict=pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [8]:
data={
    'Name':['Krish','John','Jack'],
    'Age':[20,30,40],
    'City':['Bangalore','New York','Florida']
}
df=pd.DataFrame(data)
print(df)
print(type(df))
df

    Name  Age       City
0  Krish   20  Bangalore
1   John   30   New York
2   Jack   40    Florida
<class 'pandas.core.frame.DataFrame'>

    Name  Age       City
0  Krish   20  Bangalore
1   John   30   New York
2   Jack   40    Florida

In [9]:
import numpy as np
print(np.array(df))

[['Krish' 20 'Bangalore']
 ['John' 30 'New York']
 ['Jack' 40 'Florida']]

In [11]:
df['Name']
type(df['Name'])

pandas.core.series.Series

In [13]:
df.head(2)
df.tail(1)

   Name  Age     City
2  Jack   40  Florida

In [14]:
df.loc[0]

Name        Krish
Age            20
City    Bangalore
Name: 0, dtype: object

In [16]:
df.iloc[0][0]

C:\Users\KASHISH\AppData\Local\Temp\ipykernel_9532\2900375399.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][0]

'Krish'

In [15]:
df.iloc[0]

Name        Krish
Age            20
City    Bangalore
Name: 0, dtype: object

In [17]:
df.iloc[0][2]

C:\Users\KASHISH\AppData\Local\Temp\ipykernel_9532\2519637664.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][2]

'Bangalore'

In [21]:
print(df.at[1,'Age'])
print(df.at[2,'Name'])
print(df.iat[2,2])

30
Jack
Florida

In [23]:
df['Salary']=[500000,600000,700000]
df

    Name  Age       City  Salary
0  Krish   20  Bangalore  500000
1   John   30   New York  600000
2   Jack   40    Florida  700000

In [25]:
df.drop('Salary',axis=1)

    Name  Age       City
0  Krish   20  Bangalore
1   John   30   New York
2   Jack   40    Florida

In [27]:
df

    Name  Age       City  Salary
0  Krish   20  Bangalore  500000
1   John   30   New York  600000
2   Jack   40    Florida  700000

In [ ]:
df.drop('Salary',axis=1,inplace=True)

In [38]:
df

   Name  Age      City
1  John   31  New York
2  Jack   41   Florida

In [40]:
df.dtypes
df.describe()

             Age
count   2.000000
mean   36.000000
std     7.071068
min    31.000000
25%    33.500000
50%    36.000000
75%    38.500000
max    41.000000

In [37]:
df.drop(0,inplace=True)

In [32]:
df['Age']=df['Age']+1